### ISSUE TITLE
Strange iwlist behavior

### ISSUE THREAD

**Issue by Lukse** [8devices/carambola#10]
It is like Russian roulette. You never know what to expect. 

Here is log of several attempts to run [iwlist wlan0 scan] command.

root@OpenWrt:/# iwlist wlan0 scan
wlan0     Interface doesn't support scanning : Device or resource busy

root@OpenWrt:/# iwlist wlan0 scan
wlan0     Interface doesn't support scanning : Device or resource busy

root@OpenWrt:/# iwlist wlan0 scan
wlan0     Scan completed :
          Cell 01 - Address: 36:5A:05:E7:BC:A5
                    Channel:1
                    Frequency:2.412 GHz (Channel 1)
                    Quality=42/70  Signal level=-68 dBm  
                    Encryption key:on
                    ESSID:"iPhone"
                    Bit Rates:6 Mb/s; 9 Mb/s; 12 Mb/s; 18 Mb/s; 24 Mb/s
                              36 Mb/s; 48 Mb/s; 54 Mb/s
                    Mode:Master
                    Extra:tsf=000000000014503c
                    Extra: Last beacon: 1760ms ago
                    IE: Unknown: 00066950686F6E65
                    IE: Unknown: 01088C129824B048606C
                    IE: Unknown: 030101
                    IE: Unknown: 2A0100
                    IE: Unknown: 2F0100
                    IE: IEEE 802.11i/WPA2 Version 1
                        Group Cipher : CCMP
                        Pairwise Ciphers (1) : CCMP
                        Authentication Suites (1) : PSK
                    IE: Unknown: DD0A0017F206010103010000
                    IE: Unknown: DD0D0017F206020106145A05E7BCA4
                    IE: Unknown: DD09001018020000450000
                    IE: Unknown: DD180050F2020101800003A4000027A4000042435E0062322F00

**Comment by valinskas** [comment]
Messages below indicate that you have attempted to request scan
operation while it is already in progress. So this is not a problem I
think it is expected.

```
root@OpenWrt:/# iwlist wlan0 scan
wlan0 Interface doesn't support scanning : Device or resource busy

root@OpenWrt:/# iwlist wlan0 scan
wlan0 Interface doesn't support scanning : Device or resource busy
```

**Comment by valinskas** [comment]
```
`--> sudo iw dev wlan0 scan trigger <-- initiates scan
`--> sudo iw dev wlan0 scan trigger <-- further attempts to initiate scan will fail with -EBUSY
command failed: Device or resource busy (-16)
`--> sudo iw dev wlan0 scan trigger
command failed: Device or resource busy (-16)
`--> sudo iw dev wlan0 scan trigger
command failed: Device or resource busy (-16)
`--> sudo iw dev wlan0 scan trigger
command failed: Device or resource busy (-16)
`--> sudo iw dev wlan0 scan trigger
command failed: Device or resource busy (-16)
`--> sudo iw dev wlan0 scan trigger
command failed: Device or resource busy (-16)
`--> sudo iw dev wlan0 scan trigger
command failed: Device or resource busy (-16)
`--> sudo iw dev wlan0 scan trigger
command failed: Device or resource busy (-16)

# some time later
`--> sudo iw dev wlan0 scan trigger <-- initiates scan ok, no error.
```

This was tested on my laptop Ubuntu/12.04 LTS
