### ISSUE TITLE
can not compile any boost library

### ISSUE THREAD

**Issue by Softverk** [8devices/carambola#13]
selecting boost libraries during "make menuconfig" and then trying to compile the carambola/openWRT does not work.

for example, i selected Libraries ---> <*> boost-thread and it fails in the following manner:

.............
....................

skipped <p/carambola/carambola/build_dir/target-mipsel_r2_uClibc-0.9.33.2/boost_1_51_0/ipkg-install/lib>libboost_context.so for lack of <p/carambola/carambola/build_dir/target-mipsel_r2_uClibc-0.9.33.2/boost_1_51_0/ipkg-install/lib>libboost_context.so.1.51.0...
gcc.compile.c++ bin.v2/libs/context/build/gcc-mipsel/release/link-static/threading-multi/fcontext.o
libs/context/src/fcontext.cpp: In function 'void\* boost::ctx::detail::align_stack(void*)':
libs/context/src/fcontext.cpp:25:21: error: 'uintptr_t' was not declared in this scope
libs/context/src/fcontext.cpp:25:32: error: expected ')' before 'base'
libs/context/src/fcontext.cpp:26:66: error: expected ')' before ';' token
libs/context/src/fcontext.cpp:26:66: error: expected ')' before ';' token

"mipsel-openwrt-linux-gcc"  -ftemplate-depth-128 -Os -pipe -mips32r2 -mtune=mips32r2 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float -O3 -finline-functions -Wno-inline -Wall -Os -pipe -mips32r2 -mtune=mips32r2 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float  -DBOOST_ALL_NO_LIB=1 -DNDEBUG  -I"." -c -o "bin.v2/libs/context/build/gcc-mipsel/release/link-static/threading-multi/fcontext.o" "libs/context/src/fcontext.cpp"

...failed gcc.compile.c++ bin.v2/libs/context/build/gcc-mipsel/release/link-static/threading-multi/fcontext.o...
...skipped <pbin.v2/libs/context/build/gcc-mipsel/release/link-static/threading-multi>libboost_context.a(clean) for lack of <pbin.v2/libs/context/build/gcc-mipsel/release/link-static/threading-multi>fcontext.o...
...skipped <pbin.v2/libs/context/build/gcc-mipsel/release/link-static/threading-multi>libboost_context.a for lack of <pbin.v2/libs/context/build/gcc-mipsel/release/link-static/threading-multi>fcontext.o...
...skipped <p/carambola/carambola/build_dir/target-mipsel_r2_uClibc-0.9.33.2/boost_1_51_0/ipkg-install/lib>libboost_context.a for lack of <pbin.v2/libs/context/build/gcc-mipsel/release/link-static/threading-multi>libboost_context.a...
...failed updating 2 targets...
...skipped 6 targets...
make[3]: **\* [/carambola/carambola/build_dir/target-mipsel_r2_uClibc-0.9.33.2/boost_1_51_0/.built] Error 1
make[3]: Leaving directory `/carambola/carambola/feeds/packages/libs/boost'
make[2]: *** [package/feeds/packages/boost/compile] Error 2
make[2]: Leaving directory`/carambola/carambola'
make[1]: **\* [/carambola/carambola/staging_dir/target-mipsel_r2_uClibc-0.9.33.2/stamp/.package_compile] Error 2
make[1]: Leaving directory `/carambola/carambola'
make: **\* [world] Error 2

the issue is also reported here: http://www.8devices.com/community/viewtopic.php?f=6&t=322

**Comment by Softverk** [comment]
from openwrt , it seems there is a patch for it there: https://dev.openwrt.org/browser/packages/libs/boost/patches/200-cstdint_missing_include.patch?rev=34635

may be it should be incorporated into here.

just tested the patch and it works

**Comment by valinskas** [comment]
Hi,

I pulled changes from upstream and pushed out to 8devices/packages repository.
You can use `./script/feeds update packages` and it should pull all in changes.
