### ISSUE TITLE
packages and trunk out of sync

### ISSUE THREAD

**Issue by fettlaus** [8devices/carambola#14]
Some packages have moved from /packages to /trunk in the main OpenWRT repository and are also no longer available in your Github mirror 8devices/packages.
(e.g. libevent2 or libsysfs)

This means, that the 8devices/packages can no longer be used in feeds.conf because there are now some dependencies missing.

**Comment by valinskas** [comment]
Yes, I am aware of that. I intend to merge openwrt upstream to carambola/v2.5 -- the problem will go away then.

**Comment by fettlaus** [comment]
Great. I'll just use a fork until then. Thanks.
