### ISSUE TITLE
Issue with compiling the master branch

### ISSUE THREAD

**Issue by ibitbang** [8devices/carambola#19]
/home/xxxxxx/Projects/DevelBuilds/carambola/tmp/dl/hotplug2-201.tar.gz /home/xxxxxx/Projects/DevelBuilds/carambola/dl/ && rm -rf hotplug2-201; 
Checking out files from the svn repository...
svn: E670002: Unable to connect to a repository at URL 'http://svn.nomi.cz/svn/isteve/hotplug2'
svn: E670002: Name or service not known
svn: E670002: Unable to connect to a repository at URL 'http://svn.nomi.cz/svn/isteve/hotplug2'
svn: E670002: Name or service not known
make[3]: **\* [/home/xxxxxx/Projects/DevelBuilds/carambola/dl/hotplug2-201.tar.gz] Error 1
make[3]: Leaving directory `/home/xxxxxx/Projects/DevelBuilds/carambola/package/hotplug2'
make[2]: *** [package/hotplug2/compile] Error 2
make[2]: Leaving directory`/home/aditya/Projects/DevelBuilds/carambola'
make[1]: **\* [/home/xxxxxx/Projects/DevelBuilds/carambola/staging_dir/target-mipsel_r2_uClibc-0.9.33.2/stamp/.package_compile] Error 2
make[1]: Leaving directory `/home/xxxxxx/Projects/DevelBuilds/carambola'

**Comment by ibitbang** [comment]
I got this after the latest tip from the repo I synced today

**Comment by assarbad** [comment]
@adigandhi you should close the ticket then :)

**Comment by ibitbang** [comment]
@assarbad , thanks for reminding. Done!

**Comment by assarbad** [comment]
Side-note for readers: [this StackOverflow answer](http://stackoverflow.com/a/25366936) addresses one way of working around this issue.
